apiVersion: v1
kind: Pod
metadata:
  name: tmp-shell
spec:
  containers:
  - image: ar2pi/tmp-shell:latest
    imagePullPolicy: Always
    name: shell
    resources:
      requests:
        memory: "256Mi"
        cpu: "500m"
      limits:
        memory: "256Mi"
        cpu: "500m"
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  securityContext:
    runAsUser: 1000
  terminationGracePeriodSeconds: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Never
